name: qr_flutter
description: >
  Fork of QR.Flutter
version: 4.0.2
homepage: https://github.com/theyakka/qr.flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5

flutter:
  uses-material-design: false
